services:
  #backend:
  
  #frontend:

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - transcendence
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    #depends_on:
    #  - backend
    #  - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/stub_status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  nginx_exporter:
    container_name: nginx_exporter
    image: nginx/nginx-prometheus-exporter
    networks:
      - transcendence
    ports:
      - "9113:9113"
    command:
    - "-nginx.scrape-uri=http://nginx:80/stub_status"
    depends_on:
      nginx:
        condition: service_healthy

    restart: unless-stopped

  vault:
    container_name: vault
    image: hashicorp/vault
    networks:
      - transcendence
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_LISTEN_ADDRESS: ${VAULT_DEV_LISTEN_ADDRESS}
      VAULT_ADDR: ${VAULT_ADDR}
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    command: vault server -dev
    cap_add:
      - IPC_LOCK #evita que secrets sejam escritos no disco (swap), permite ao vault bloquear memória
    restart: unless-stopped
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - transcendence
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD} 
    volumes:
      - grafana-db:/var/lib/grafana/
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    networks:
      - transcendence
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/var/lib/prometheus/data
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    command: redis-server --appendonly yes
    networks:
      - transcendence
    ports:
      - "6379:6379"
    volumes:
        - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis_exporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter
    networks:
      - transcendence
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  postgres:
      container_name: postgres
      image: postgres:16
      networks:
        - transcendence
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 5s
        timeout: 3s
        retries: 5
        start_period: 10s
      restart: unless-stopped

  postgres_exporter:
      container_name: postgres_exporter
      image: prometheuscommunity/postgres-exporter
      networks:
        - transcendence
      environment:
        DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      ports:
        - "9187:9187"
      depends_on: 
        postgres:
          condition: service_healthy
      restart: unless-stopped
    
volumes:
  grafana-db:
  prometheus-data:
  redis-data:
  postgres-data:


networks:
  transcendence:
    driver: bridge