events {}

http {

    server {
        listen 80;
        listen [::]:80;

        server_name Transcendence;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name Transcendence;

        ssl_protocols TLSv1.2 TLSv1.3;

        ssl_certificate /etc/nginx/certs/nginx.cert;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        #location / {
        #    proxy_pass http://frontend:3000;
        #}

        #location /api/ {
        #    proxy_pass http://backend:8000;
        #}

        #location /ws {
        #    proxy_pass http://backend:8000;
        #    proxy_set_header Upgrade $http_upgrade;
        #    proxy_set_header Connection "upgrade";
        #}

        location /stub_status {
            stub_status on;
            allow 172.0.0.0/8;
            deny all;
        }
    }
}