global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]
  - job_name: "backend"
    static_configs:
      - targets: ["backend:4000"]
  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"] 
  - job_name: "postgres" #database
    static_configs:
      - targets: ["postgres_exporter:9187"]